### ISSUE TITLE
can this make a folder automatically and drop the clipboard contents into it?

### ISSUE THREAD

**Issue by sibjac** [saurabhwahile/ExcelDistributeFilesAssignWork#1]
can this make a folder automatically with the name of "y" each time and paste the clipboard contents into it with each raw input?

**Comment by saurabhwahile** [comment]
I assume it won't. Since the paste functionality is controlled by the OS(in this case Windows)

However, I would suggest using another software in conjunction with it, say, AutoHotKey, to run a script that creates a folder and drops the clipboard contents into it.

**Comment by sibjac** [comment]
I was wondering if it could create a folder each time for the "y" and use the pyperclip or tkinter modules to help with pasting contents to it....

**Comment by saurabhwahile** [comment]
As I've said, the paste functionality is controlled by the OS, you cannot modify it, however what you can do, is, use a proxy script assigned to a hotkey, say `Ctrl+K` and run it when you wish to paste.

pypaperclip does not support filesystem.

**Comment by sibjac** [comment]
thank you for your prompt reply...
